added task about 3 button
FE38-Front-End/Mikita_Papok pull request #8
Opened 2020-12-06 07:19 UTC by mikitapapok

Задача про три кнопки с выводом и удалением элемента списка

2020-12-07 12:39 UTC, akhovbok requested changes

2020-12-07 12:39 UTC, akhovbok commented on lesson20/task1.js
> +    return document.body.appendChild(createList);
return не нужен

2020-12-07 12:39 UTC, akhovbok commented on lesson20/task1.js
> +    const createListElement = document.createElement('li');
название не соответствует действительности createListElement  подходит для названия метода но никак не переменной createdListElement  гораздо более понятное название для переменной

2020-12-07 12:39 UTC, akhovbok commented on lesson20/task1.js
> +    createListElement.textContent = `${date.getHours()}: ${date.getMinutes()}`;
дата никогда не будет меняться

2020-12-07 12:39 UTC, akhovbok commented on lesson20/task1.js
> +const createList = document.createElement('ul');
название пермененной не подходит

2020-12-07 12:39 UTC, akhovbok commented on lesson20/task1.js
> +    if (document.getElementsByClassName('list').length > 0) {
'list' - имя класса стоит вынести в константу, поскольку во многих местах именно на него ссылается код

2020-12-14 10:58 UTC, mikitapapok commented on lesson20/task1.js
> +    if (document.getElementsByClassName('list').length > 0) {
исправил замечания

2020-12-21 13:29 UTC, akhovbok approved these changes

2020-12-22 16:01 UTC, merged