added lesson21
FE38-Front-End/Mikita_Papok pull request #9
Opened 2020-12-08 09:55 UTC by mikitapapok

Совсем забыл hrml и css, поэтому оформление такое убогое. Отпиши, пожалуйста, что здесь исправить

2020-12-24 09:39 UTC, akhovbok requested changes

2020-12-24 09:39 UTC, akhovbok commented on lesson21/index.html
> +            </button>
зачем такие большие отступы между строками?

2020-12-24 09:39 UTC, akhovbok commented on lesson21/style.css
> +
форматирование все еще страдает

2020-12-24 09:39 UTC, akhovbok commented on lesson21/style.css
> +#right {
мы не пишем селекторы по id

2020-12-24 09:39 UTC, akhovbok commented on lesson21/style.css
> +    right: -15%;
почему в процентах?

2020-12-24 09:39 UTC, akhovbok commented on lesson21/task.js
> +const inputSide = document.getElementsByClassName('input-side')[0];
Никита ты делаешь прогресс в наименованиях, но все еще иногда я не понимаю за что отвечает переменная

2020-12-24 09:39 UTC, akhovbok commented on lesson21/task.js
> +    square.style.border = '1px solid black';
что то мне подсказывает что бордер можно было бы и в стили поместить

2020-12-24 09:39 UTC, akhovbok commented on lesson21/task.js
> +        circle.style.border = `1px solid black`;
нет необходимости в обратных кавычках для этой строки

2020-12-24 09:39 UTC, akhovbok commented on lesson21/task.js
> +        circle.style.borderRadius = '100%';
имеет смысл это держать в стилях

2020-12-24 09:39 UTC, akhovbok commented on lesson21/task.js
> +    let fringle = ((side / 2) - (diam / 2)) * (-1);
много круглых скобок лишних

2020-12-24 09:39 UTC, akhovbok commented on lesson21/task.js
> +down.addEventListener('click', event => {
дилегирование?

2020-12-28 07:15 UTC, mikitapapok commented on lesson21/style.css
> +
исправил

2020-12-28 07:15 UTC, mikitapapok commented on lesson21/index.html
> +            </button>
исправил

2021-01-30 08:34 UTC, akhovbok approved these changes

2021-02-02 12:33 UTC, merged